modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0-only"
[[mods]]
modId="rubidium"
version="${version}"
displayName="Rubidium"
logoFile="icon.png"
description='''
Rubidium is a Unofficial Fork of the Sodium maked to work on FML.
'''
credits="NanoLive, Asek3"
authors="JellySquid"